name: "R-Type Build"

on:
  workflow_call:
    inputs:
      EXECUTABLES:
        description: "Coma-separated list of executables to check"
        required: true
        type: string

env:
  CONAN_VERSION: "2.10.2"

jobs:
  build:
    name: "Test CMake and verify executables"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install `libudev` package, required for build with Conan"
        run: "sudo apt install libudev-dev libgl-dev libgl1-mesa-dev libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxfixes-dev libxi-dev libxinerama-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxres-dev libxss-dev libxtst-dev libxv-dev libxxf86vm-dev libxcb-glx0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-res0-dev libxcb-util-dev libxcb-util0-dev -y"

      - name: Install Conan
        uses: "turtlebrowser/get-conan@main"

      - name: "Setup cmake"
        uses: "jwlawson/actions-setup-cmake@v2"

      - name: "Build executables"
        run: ./build.sh

      - name: "Verify executables"
        timeout-minutes: 2
        run: |
          for executable in ${EXECUTABLES//,/ }; do
            if [ ! -x "$executable" ]; then
              echo "::error file=$executable,title=Executable problem::This executable does not exist or is not executable"
              exit 1
            fi
          done

      - name: "Check for un-encapsulated GLibC usage in executables"
        timeout-minutes: 2
        run: |
          export PATH="$PATH:$(pwd)/.github/workflows/executables"
          for executable in ${EXECUTABLES//,/ }; do
            GLIBCHECKER_GH_ACTIONS="true" glib_checker "$executable"
          done
