name: Lint and format code

on:
  workflow_call:

jobs:
  lint:
    name: Lint and format code
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      #- name: Checkout
      #  uses: actions/checkout@v4
      #  with:
      #    fetch-depth: 0

      #- name: Lint and format code
      #  uses: super-linter/super-linter/slim@v7
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
