name: R-Type CI

on:
  push:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      EXECUTABLES: "r-type_server,r-type_client"

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  doxygen:
    name: Dpxygen
    #needs:
    #  - build
    #  - lint
    uses: ./.github/workflows/doxygen.yml
    permissions:
      contents: write
    secrets: inherit

  mirror:
    name: Mirror
    needs:
      - doxygen
    uses: ./.github/workflows/mirror.yml
    secrets: inherit
