name: Create a new release

on:
  workflow_call:

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest
    #if: ${{ github.ref_name == 'main' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
